version: '3.8'

services:
  websocket-server:
    build:
      context: .
    ports:
      - "3000:3000"
    # depends_on:
    #   - text-adventure

  # text-adventure:
  #   build:
  #     context: https://github.com/veryscarycary/farm-text-adventure
  #   ports:
  #     - "3001:3001"  # Example port mapping for Ruby process
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge