services:
  websocket-server:
    container_name: websocket-server
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - text-adventure
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

  text-adventure:
    container_name: text-adventure
    restart: unless-stopped
    build:
      context: https://github.com/veryscarycary/farm-text-adventure.git
      dockerfile: Dockerfile-tcp-server
    stdin_open: true  # necessary for interactive mode
    tty: true  # necessary for interactive mode
    ports:
      - "3001:3001"  # Port mapping for Ruby process
    networks:
      - my-network

networks:
  my-network:
    driver: bridge